### ISSUE TITLE
Stopped working since December

### ISSUE THREAD

**Issue by FireMakeThunder** [axilleasiv/vscode-javascript-repl-docs#41]
Has anyone else found that this fails to work at least since December or is it just me?

### Tried clean reinstall
I've tried removing and reinstalling this extension and removing and reinstalling VSCode with myself logged out and the settings sync disabled. Even then, reinstalling this extension still results in the program failing.

### Running JS Repl: Run
If I try to run the repl in the open file, I get this:
```
There is an unexpected error, would you like to submit this as issue on github? If so, please copy the contents of log file, and create an issue on github.
```
But the log file doesn't exist, and where the log file is meant to be has other log files present, but only with the latest log file being from December.

### Running JS Repl: New Javascript File (.js)
Here are some errors I get when I try to open a new file JS Repl:
```

2023-01-16 04:41:42.095 [error] TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at Style.hasDecorations (c:\Users\USER\.vscode\extensions\achil.vscode-javascript-repl-0.7.3\dist\main\extension.js:1:89262)
at c:\Users\USER\.vscode\extensions\achil.vscode-javascript-repl-0.7.3\dist\main\extension.js:1:327373
at Array.forEach (<anonymous>)
at c:\Users\USER\.vscode\extensions\achil.vscode-javascript-repl-0.7.3\dist\main\extension.js:1:327240
at d.invoke ([[PATH]]/extensionHostProcess.js:63:145)
at w.deliver ([[PATH]]/extensionHostProcess.js:63:2029)
at g.fire ([[PATH]]/extensionHostProcess.js:63:1667)
at [[PATH]]/extensionHostProcess.js:96:150378
at d.invoke ([[PATH]]/extensionHostProcess.js:63:145)
at w.deliver ([[PATH]]/extensionHostProcess.js:63:2029)
at g.fire ([[PATH]]/extensionHostProcess.js:63:1667)
at w.acceptDocumentsAndEditorsDelta ([[PATH]]/extensionHostProcess.js:96:13786)
at w.$acceptDocumentsAndEditorsDelta ([[PATH]]/extensionHostProcess.js:96:12176)
at u.N ([[PATH]]/extensionHostProcess.js:104:11208)
at u.M ([[PATH]]/extensionHostProcess.js:104:10926)
at u.H ([[PATH]]/extensionHostProcess.js:104:10019)
at u.G ([[PATH]]/extensionHostProcess.js:104:9000)
at [[PATH]]/extensionHostProcess.js:104:7788
at d.invoke ([[PATH]]/extensionHostProcess.js:63:145)
at w.deliver ([[PATH]]/extensionHostProcess.js:63:2029)
at g.fire ([[PATH]]/extensionHostProcess.js:63:1667)
at h.fire ([[PATH]]/extensionHostProcess.js:72:14314)
at [[PATH]]/extensionHostProcess.js:120:15804
at d.invoke ([[PATH]]/extensionHostProcess.js:63:145)
at w.deliver ([[PATH]]/extensionHostProcess.js:63:2029)
at g.fire ([[PATH]]/extensionHostProcess.js:63:1667)
at h.fire ([[PATH]]/extensionHostProcess.js:72:14314)
at c.y ([[PATH]]/extensionHostProcess.js:72:17324)
at [[PATH]]/extensionHostProcess.js:72:15795
at d.invoke ([[PATH]]/extensionHostProcess.js:63:145)
at w.deliver ([[PATH]]/extensionHostProcess.js:63:2029)
at g.fire ([[PATH]]/extensionHostProcess.js:63:1667)
at g.acceptChunk ([[PATH]]/extensionHostProcess.js:72:12045)
at [[PATH]]/extensionHostProcess.js:72:11332
at Socket.l ([[PATH]]/extensionHostProcess.js:72:19792)
at Socket.emit (node:events:526:28)
at addChunk (node:internal/streams/readable:315:12)
at readableAddChunk (node:internal/streams/readable:289:9)
at Readable.push (node:internal/streams/readable:228:10)
at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

2023-01-16 04:41:42.097 [error] TypeError: Cannot read properties of undefined (reading 'id')
at Style.clear (c:\Users\USER\.vscode\extensions\achil.vscode-javascript-repl-0.7.3\dist\main\extension.js:1:91712)
at Repl.setEditor (c:\Users\USER\.vscode\extensions\achil.vscode-javascript-repl-0.7.3\dist\main\extension.js:1:2715)
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Repl.run (c:\Users\USER\.vscode\extensions\achil.vscode-javascript-repl-0.7.3\dist\main\extension.js:1:3624)
at async c:\Users\USER\.vscode\extensions\achil.vscode-javascript-repl-0.7.3\dist\main\extension.js:1:310545
at async s.h ([[PATH]]/extensionHostProcess.js:94:107614) achil.repl.runCurrent {"value":"achil.vscode-javascript-repl","c":"achil.vscode-javascript-repl"}

```

`c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\`
is replaced with `[[PATH]]` to keep the code block narrow.

**Comment by chadoe** [comment]
Same, I think javascript stopped working after I upgraded my node.js to 18.14.0, typescript already stopped working before.

**Comment by axilleasiv** [comment]
@FireMakeThunder @chadoe I am so sorry that you had this issue.

@chadoe thank you so much for your comment, it was helpful. The extension had problem with the node versions >= 18. I have fixed the issues and published a new version (0.7.4) that solves these.

Please don't hesitate to let me know if you have any other issues.

**Comment by chadoe** [comment]
Thank you @axilleasiv, 0.7.4 works for me.

**Comment by shabamichael** [comment]
Hi ,
No not the first time i installed it. When i originally installed it , it was working very fine and perfect, before it suddenly stopped working.
My version of  node is node 19.6.1

regards
Michel
________________________________

**Comment by atroia** [comment]
Im having similar issues with 0.7.5 in VS Code 1.100.2, running Node v23.11.0 (installed via Homebrew), I start it and nothing happens. When I try to run it again it (because it still says "JS Repl: Run" in the menu) it just says "There is already a repl instance associated with this file" and again nothing happens.
